const DESCRIPTIONS: Record<string, string> = {
  'kernel_task': 'macOS kernel; also soaks up CPU on purpose to cool down a hot Mac',
  'launchd': 'starts and supervises every other process',
  'WindowServer': 'draws windows and everything on screen',
  'loginwindow': 'your login session',
  'Dock': 'Dock, Launchpad and Mission Control',
  'Finder': 'Finder',
  'SystemUIServer': 'menu bar extras',
  'ControlCenter': 'Control Center and menu bar status items',
  'NotificationCenter': 'notifications and widgets',
  'WindowManager': 'Stage Manager and window tiling',
  'Spotlight': 'Spotlight search UI',
  'mds': 'Spotlight indexing coordinator',
  'mds_stores': 'Spotlight is indexing files',
  'mdworker': 'Spotlight is reading files to index them',
  'mdworker_shared': 'Spotlight is reading files to index them',
  'mdsync': 'Spotlight index sync',
  'corespotlightd': 'Spotlight indexing of app content',
  'backupd': 'Time Machine is backing up',
  'backupd-helper': 'Time Machine scheduling',
  'photoanalysisd': 'Photos is analyzing your library (faces, scenes)',
  'photolibraryd': 'Photos library database',
  'mediaanalysisd': 'analyzing photos and videos for search and Live Text',
  'cloudd': 'iCloud sync',
  'bird': 'iCloud Drive sync',
  'fileproviderd': 'cloud file sync (iCloud Drive, Dropbox, Google Drive)',
  'nsurlsessiond': 'background downloads and uploads for apps',
  'softwareupdated': 'checking for or installing macOS updates',
  'installd': 'installing apps or updates',
  'mobileassetd': 'downloading system assets (fonts, voices, ML models)',
  'syspolicyd': 'Gatekeeper is checking apps before they run',
  'XProtect': 'malware scan',
  'XprotectService': 'malware scan',
  'xprotectd': 'malware scan',
  'trustd': 'certificate checks',
  'securityd': 'keychain and security services',
  'secd': 'keychain sync',
  'tccd': 'privacy permissions (camera, files, screen recording)',
  'opendirectoryd': 'user accounts and directory services',
  'cfprefsd': 'app preferences',
  'logd': 'system log',
  'fseventsd': 'tracks file changes for apps',
  'distnoted': 'delivers system notifications between processes',
  'configd': 'network configuration',
  'mDNSResponder': 'DNS and Bonjour',
  'symptomsd': 'network diagnostics',
  'airportd': 'Wi-Fi',
  'bluetoothd': 'Bluetooth',
  'coreaudiod': 'audio',
  'locationd': 'location services',
  'powerd': 'power management and sleep',
  'thermalmonitord': 'thermal monitoring',
  'diskarbitrationd': 'mounting disks',
  'kernelmanagerd': 'kernel extensions',
  'hidd': 'keyboard, mouse and trackpad input',
  'dasd': 'schedules background work for when the Mac is idle',
  'apsd': 'Apple push notifications',
  'UserEventAgent': 'reacts to system events',
  'runningboardd': 'manages app lifecycle and resource limits',
  'containermanagerd': 'app sandbox containers',
  'sharingd': 'AirDrop, Handoff and sharing',
  'rapportd': 'communication with your other Apple devices',
  'ReportCrash': 'writing a crash report',
  'spindump': 'recording a hang or slowdown report',
  'sysmond': 'system statistics for Activity Monitor and similar tools',
  'mediaremoted': 'Now Playing media controls',
  'akd': 'Apple Account authentication',
  'deleted': 'freeing purgeable disk space',
  'lsd': 'app registry (which app opens which file)',
  'iconservicesagent': 'app icons',
  'quicklookd': 'Quick Look previews',
  'QuickLookUIService': 'Quick Look previews',
  'VTDecoderXPCService': 'hardware video decoding for apps',
  'VTEncoderXPCService': 'hardware video encoding for apps',
  'MTLCompilerService': 'compiling GPU shaders for an app',
  'com.apple.WebKit.WebContent': 'a web page in Safari or an app using WebKit',
  'com.apple.WebKit.GPU': 'GPU work for WebKit web pages',
  'com.apple.WebKit.Networking': 'network requests for WebKit web pages',
  'xpcproxy': 'launching a system service',
  'assistantd': 'Siri',
  'corespeechd': 'listens for "Hey Siri"',
  'universalaccessd': 'accessibility features',
  'screencaptureui': 'screenshot and screen recording UI',
  'AMPDeviceDiscoveryAgent': 'looking for iPhones and iPads to sync',
  'nehelper': 'VPN and network extensions',
  'neagent': 'VPN and network extensions',
}

export const describeMacosProcess = (name: string): string | null => DESCRIPTIONS[name] ?? null

const MACOS_PATH_PREFIXES = ['/System/', '/usr/libexec/', '/usr/sbin/', '/usr/bin/', '/sbin/', '/bin/', '/Library/Apple/']

export const isMacosPath = (command: string) =>
  MACOS_PATH_PREFIXES.some(prefix => command.startsWith(prefix)) || command in DESCRIPTIONS
